name: ptes
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pydantic
  - xlsxwriter
  - cx_freeze
  - rich
  - loguru
  - pip
  - pip:
    - pyside6
  # dev
  - pytest
  - hypothesis
  - mypy
  - pylint
  - ruff
